version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    depends_on:
      config-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-eureka-service
    hostname: localhost
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"

  config-service:
    build: config-service/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8891:8891
    healthcheck:
      test: "exit 0"

  api-gateway:
    build: zuul-apigateway/
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      restaurant-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-zuul-service
    hostname: localhost
    ports:
      - 8092:8092
    healthcheck:
      test: "exit 0"

  restaurant-service:
    build: restaurant-service/
    image: demo-restaurant-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  user-service:
    build: user-service/
    image: demo-user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080
    depends_on:
      config-service:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
